openapi: "3.0.1"
info:
  title: API Products
  version: "1.0"
paths:
  /api/dbCarts/{cid}:
    get:
      summary: Obtiene el carrito del usuario con los productos agregados
      tags:
        - Carts
      parameters:
        - name: uid
          in: path
          required: true
          description: id del carrito enlazado con el usuario
      responses:
        "200":
          description: Carrito obtenido con exito
          content:
            application/json:
              schema:
                type: object
                carts:
                  $ref: "#/components/schemas/Cart"
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbiden
        "500":
          description: Internal Server Error




'/':
  get:
    summary: Crea un nuevo carrito.
    responses:
      '201':
        description: Nuevo carrito creado con éxito.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      '500':
        description: Error interno del servidor.

'/:cartId/:productId':
  post:
    summary: Agrega un producto a un carrito.
    parameters:
      - name: cartId
        in: path
        description: ID del carrito.
        required: true
        schema:
          type: string
      - name: productId
        in: path
        description: ID del producto.
        required: true
        schema:
          type: string
    responses:
      '200':
        description: Producto agregado al carrito con éxito.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      '401':
        description: No tienes permiso para agregar este producto.
      '500':
        description: Error interno del servidor.

'/:cid/products/:pid':
  delete:
    summary: Elimina un producto de un carrito.
    parameters:
      - name: cid
        in: path
        description: ID del carrito.
        required: true
        schema:
          type: string
      - name: pid
        in: path
        description: ID del producto.
        required: true
        schema:
          type: string
    responses:
      '200':
        description: Producto eliminado del carrito con éxito.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      '500':
        description: Error interno del servidor.
  put:
    summary: Actualiza la cantidad de un producto en el carrito.
    parameters:
      - name: cid
        in: path
        description: ID del carrito.
        required: true
        schema:
          type: string
      - name: pid
        in: path
        description: ID del producto.
        required: true
        schema:
          type: string
    requestBody:
      description: Cantidad de producto a actualizar.
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              quantity:
                type: number
    responses:
      '200':
        description: Carrito actualizado con éxito.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      '500':
        description: Error interno del servidor.

'/:cid':
  put:
    summary: Actualiza el carrito con un arreglo de productos.
    parameters:
      - name: cid
        in: path
        description: ID del carrito.
        required: true
        schema:
          type: string
    requestBody:
      description: Arreglo de productos para actualizar el carrito.
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              productos:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    responses:
      '200':
        description: Carrito actualizado con éxito.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      '500':
        description: Error interno del servidor.
  delete:
    summary: Elimina todos los productos del carrito.
    parameters:
      - name: cid
        in: path
        description: ID del carrito.
        required: true
        schema:
          type: string
    responses:
      '200':
        description: Todos los productos eliminados del carrito con éxito.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      '500':
        description: Error interno del servidor.
  get:
    summary: Obtiene el carrito por su ID.
    parameters:
      - name: cid
        in: path
        description: ID del carrito.
        required: true
        schema:
          type: string
    responses:
      '200':
        description: Carrito obtenido con éxito.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      '500':
        description: Error interno del servidor.

'/:cid/purchase':
  get:
    summary: Realiza la compra final del carrito.
    parameters:
      - name: cid
        in: path
        description: ID del carrito.
        required: true
        schema:
          type: string
    responses:
      '200':
        description: Compra realizada con éxito.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseData'
      '500':
        description: Error interno del servidor.





components:
  schemas:
    Cart:
      type: object
      properties:
        productos:
          type: array
          description: Productos que el usuario agregó al carrito
          items:
            type: object
            properties:
              product:
                type: string
                description: ID del producto
              quantity:
                type: number
                description: Número de unidades del producto (por defecto es 1)
                